workflows:
  react-native-android:
    name: React Native Android Debug Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.napnetworks.app"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your_email@example.com # Replace with your email to receive build notifications
        notify:
          success: true
          failure: true
